# Generated by Django 5.2.4 on 2025-08-21 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_change_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='last_change_type',
            field=models.CharField(choices=[('update', 'Update'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('delete', 'Delete'), ('created', 'Created')], default='created', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['last_change_type'], name='orders_orde_last_ch_b354c6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['last_change_at'], name='orders_orde_last_ch_9365fc_idx'),
        ),
    ]
